[package]
name = "distributed_analytics_system"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
axum = { version = "0.6", features = ["headers"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
duckdb = { version = "0.8" }
reqwest = { version = "0.11", features = ["json"] }
raft = "0.7"
slog = "2.7"
slog-term = "2.9"
slog-async = "2.7"
thiserror = "1.0"
async-trait = "0.1"
bytes = "1.4"
uuid = { version = "1.3", features = ["v4"] }
prometheus = "0.13"
lazy_static = "1.4"

[dev-dependencies]
tokio-test = "0.4"
assert_matches = "1.5"

[[bin]]
name = "distributed_analytics_system"
path = "src/main.rs"

[[bin]]
name = "worker"
path = "src/worker.rs"