global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'raftmetrics'
    static_configs:
      - targets: ['control:8080', 'worker-1:8081', 'worker-2:8082']
    metrics_path: /metrics
    scheme: http

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
